### ISSUE TITLE
Problem with GUI

### ISSUE THREAD

**Issue by givison** [dynverse/dyno#27]
Hi,

Whenever I try running the GUI in guidelines_shiny() I get this error over and over in the console:

![image](https://user-images.githubusercontent.com/6775088/46839169-6f790200-cd71-11e8-9dd0-b138b0af4ae0.png)

It seems to mostly show up when I'm pressing a button, and the numbers vary based on which button I'm pressing. When I finally try to "close and use", the app never closes.

I've been able to get the tutorial to work using the command line guidelines() function, but I'm finding the documentation for answer_questions() quite opaque so I have no idea how to set options manually...

Thanks!
Geoff

**Comment by givison** [comment]
Sorry, this seems to have been an idiosyncrasy of that particular session... When I restarted R and reloaded the libraries the GUI worked fine. Wish I'd saved the configuration in case anyone else has the issue but oh well...

**Comment by zouter** [comment]
I saw this before. It's because the `collapse` function was deprecated in the glue package and replaced by `glue_collapse`, but this deprecation happened quite sudden so a lot of our code suddenly stopped working.

Thanks for trying out the tools! Sorry for the opaque documentation, this is still a work in progress while we try to finish up the paper etc... We will improve this soon.
