### ISSUE TITLE
Dyno installation fails: tries to install "unknown package"

### ISSUE THREAD

**Issue by mcsimenc** [dynverse/dyno#96]
Hi, I'm excited about using dyno.

I tried to install dyno to R v4.0.2 using devtools::install_github("dynverse/dyno")

It installs some packages and then fails, giving the following error:

Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 75.80.49.44. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2020-11-02 22:25:13 UTC

  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.

Any idea what is wrong and how to fix it?

Thanks!

Matt

**Comment by rcannood** [comment]
Hello Matt!

It seems you already found a solution to your problem -- that's great! 

The solution will have been to get a Github Personal Access token from Github and add it to your R environ with the instructions given above.

The problem arises due to many of the dynverse packages still not being on CRAN. This should be solved in the future, as I'm submitting the dyno packages to CRAN every now and again.

Kind regards,
Robrecht

**Comment by mcsimenc** [comment]
Thanks Robrecht!
